### ISSUE TITLE
같이전시 모집글 수정/삭제 구현

### ISSUE THREAD

**Issue by leejoonsang** [Museum-Mate/museum-mate-be#105]
## :raising_hand: 요구사항
**endpoint** : 
`PUT /api/v1/gatherings/{gatheringId}`
`DELETE /api/v1/gatherings/{gatheringId}`

같이전시 모집글을 수정하고 삭제하는 기능을 구현합니다.

## :heavy_check_mark: 체크 리스트
- [x] 같이전시 모집글 수정 기능 구현
- [x] 같이전시 모집글 삭제 기능 구현

**:pushpin: Test Code**
- [x] 같이전시 모집글 수정 성공
- [x] 같이전시 모집글 수정 실패 - case(작성자 불일치, 인증실패)
- [x] 같이전시 모집글 삭제 성공
- [x] 같이전시 모집글 삭제 실패 - case(작성자 불일치, 인증실패)

**Comment by geuun** [comment]
#117
