### ISSUE TITLE
Gallery 테이블 수정

### ISSUE THREAD

**Issue by ahn-ji0** [Museum-Mate/museum-mate-be#116]
## :raising_hand: 요구사항

현재 gallery_location에 갤러리명이 들어가있고 gallery_id(gallery와 조인된 부분)에는 null 값이 들어가있음. 이로 인해 response 부분에서 exhibition.getGallery.getId를 할때 오류가 발생!

따라서 **갤러리 테이블을 분리**하는 작업이 필요함

## :heavy_check_mark: 체크 리스트
- [ ] gallery table 분리
- [ ] open_time, close_time은 제거, address는 아직 정보는 없지만 나중을 위해서 남겨둘 것

**:pushpin: Test Code**
- [ ] 작성해야 할 테스트 코드를 작성해주세요.

## :memo: 기타 사항
(Optional) 메모할 내용이 있으면 작성해주세요.

**Comment by geuun** [comment]
#141
