### ISSUE TITLE
전시 목록 조회

### ISSUE THREAD

**Issue by moomineee** [Museum-Mate/museum-mate-be#13]
## :raising_hand: 요구사항
**endpoint** : `GET /exhibition`
크롤링한 모든 전시 목록 데이터를 반환
한 페이지 당 20개의 전시 목록 제공

## :heavy_check_mark: 체크 리스트
- [ ] name(이름), startsAt(시작날짜), endsAt(종료날짜), price(가격), location(위치) 값을 반환하는지

**:pushpin: Test Code**
- [ ] 해당 endpoint로 들어갔을 때 name, startsAt, endsAt, price, location를 성공적으로 반환

**Comment by geuun** [comment]
아직 해당 PR이 병합되지 않아서 In Progress로 옮겨두었습니다 :)
