### ISSUE TITLE
ExhibitionWriteRequest toEntity 메서드 수정

### ISSUE THREAD

**Issue by hyeonju01** [Museum-Mate/museum-mate-be#135]
## :raising_hand: 요구사항
https://github.com/Museum-Mate/museum-mate/blob/b5b4d9a5ee1dc15935391f2b5dca5644026e35f5/src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionWriteRequest.java#L28
https://github.com/Museum-Mate/museum-mate/blob/b5b4d9a5ee1dc15935391f2b5dca5644026e35f5/src/main/java/com/dev/museummate/domain/dto/exhibition/ExhibitionWriteRequest.java#L29
startsAt, endsAt을 엔티티 변경사항에 맞춰 작성해주세요.

## :heavy_check_mark: 체크 리스트
x

**:pushpin: Test Code**
x

## :memo: 기타 사항
None

**Comment by geuun** [comment]
#126 
제가 해당 이슈에서 처리한 것 같아요!
확인 해보시고 수정 안되있으면 태그해주세요!

**Comment by hyeonju01** [comment]
확인했습니다!
