### ISSUE TITLE
함께전시 모집글 조회 기능

### ISSUE THREAD

**Issue by leejoonsang** [Museum-Mate/museum-mate-be#93]
## :raising_hand: 요구사항
**endpoint** : `GET /api/v1/gathering`
**endpoint** : `GET /api/v1/gathering/{gatheringId}`

같이 전시회를 보러가는 모집글 전체와 상세 게시물을 조회할 수 있는 기능

## :heavy_check_mark: 체크 리스트
- [x] 게시물 전체 리스트 조회 기능 구현
- [x] 게시물 상세 조회 기능 구현

**:pushpin: Test Code**
- [x] 게시물 전체 리스트 조회 성공
- [x] 게시물 상세 조회 성공
- [x] 게시물 상세 조회 실패 

## :memo: 기타 사항
(Optional) 메모할 내용이 있으면 작성해주세요.

**Comment by geuun** [comment]
#107 
에서 해결된 이슈입니다
이슈 닫겠습니다 👍
